version: '3.3'


volumes:
  sqlserver_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=12345678@Ab
      - MYSQL_PASSWORD=12345678@Ab
      - MYSQL_ROOT_PASSWORD=12345678@Ab
      - MYSQL_DATABASE=YouTubeDB          
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always        
    
